### ISSUE TITLE
Lightstudio panel causing crash

### ISSUE THREAD

**Issue by Tuxxedo46** [leomoon-studios/blender-light-studio#80]
When opening Light Studio Panel I receive the following error on Blender 4.0 & 4.0.2. The error causes a instant crash or frozen program

On a fresh install the plugin works until you restart blender.

Python: Traceback (most recent call last):
  File "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\leomoon-lightstudio-master\operators\modal.py", line 415, in invoke
    panel_global = Panel(Vector((15, 45)), pw, pw*(9/16))
  File "C:\Users\...\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\leomoon-lightstudio-master\operators\modal_utils.py", line 340, in __init__
    self.button_fast_3d_edit = Button(Vector((0,0)), f'Light Brush [{kmi.type}]')
AttributeError: 'NoneType' object has no attribute 'type'  # Error

Any assistance would be great
Thank you :)

**Comment by leomoon** [comment]
this should be fixed in LightStudio 2.15.1.

Please make sure the old LightStudio version is removed.

**Comment by shanegoudy** [comment]
I'm still having this issue

**Comment by leomoon** [comment]
what timezone are you in?

I can give you remote assistance. I'm in PST.

**Comment by leomoon** [comment]
The latest version works ok in Blender 5.1. Closing this for now.
